# Onde os arquivos estáticos (build) estão.
# O Dockerfile copia o build para este local.
root /usr/share/nginx/html;

# O arquivo padrão para carregar
index index.html;

# Bloco de localização principal
location / {
    # Esta linha é a correção:
    # Tenta servir o arquivo ($uri), ou o diretório ($uri/), 
    # se falhar, retorna o index.html, permitindo o roteamento do React/Vue/Angular
    try_files $uri $uri/ /index.html; 
}


